# Generated by Django 5.2.7 on 2025-11-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication_year',
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
